theme: jekyll-theme-minimal
title: Terminal Dusk Records
logo: /assets/img/logo.png



collections:
  artists:
    output: true
    permalink: /artists/:name/
  releases:
    output: true
    permalink: /releases/:name/